### ISSUE TITLE
Dividing Zero by Zero breaks the calculator.

### ISSUE THREAD

**Issue by pauliesnug** [WebDevSimplified/Vanilla-JavaScript-Calculator#12]
When I divide 0 by 0 it breaks until I press AC. Dividing 3 by 8 gives infinity but 0 by 0 gives nothing and it stops working.

**Comment by amjadnoor** [comment]
@EthanDevelops 
I corrected your statement here.
>When I divide 0 by 0 it breaks until I press AC. Dividing <del>3 by 8 </del>any number by 0 gives infinity but 0 by 0 gives nothing and it stops working.

@WebDevSimplified 
Please check this bug and fix it.

**Comment by Nikhil27b** [comment]
#19  @WebDevSimplified  I fixed this error only pull my request.

**Comment by chasekhandelwal** [comment]
Yes same here
